/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicomfacauca.app.vista;

import com.unicomfacauca.app.controlador.EstudianteJpaController;
import com.unicomfacauca.app.modelo.Estudiante;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author aleja
 */
public class IniciarSesionJFrame extends javax.swing.JFrame {
    
    private EstudianteJpaController jpa;

    /**
     * Creates new form IniciarSesionJFrame
     */
    public IniciarSesionJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);        
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/colores_inicio_sesion.jpg"));
        Icon icon = new ImageIcon(imagen.getImage().getScaledInstance(lblImagenIniciarSesion.getWidth(), lblImagenIniciarSesion.getHeight(), Image.SCALE_DEFAULT));
        lblImagenIniciarSesion.setIcon(icon);
        jpa = new EstudianteJpaController();
        this.txtClave.setText("admin");
        this.txtUsuario.setText("alexa");
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblClave = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        chDocente = new javax.swing.JCheckBox();
        btnIniciarSesion = new javax.swing.JButton();
        lblImagenIniciarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 500, 250));
        setFocusTraversalPolicyProvider(true);
        setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(500, 250));
        setName("Iniciar Sesión"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(500, 250));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserName.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblUserName.setText("Nombre de Usuario");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, 30));

        lblClave.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblClave.setText("Contraseña");
        getContentPane().add(lblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 130, -1));

        txtUsuario.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 280, 30));

        txtClave.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 280, 30));

        chDocente.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        chDocente.setText("¿Es docente?");
        chDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chDocenteActionPerformed(evt);
            }
        });
        getContentPane().add(chDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 280, -1));

        btnIniciarSesion.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 250, 60));
        getContentPane().add(lblImagenIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chDocenteActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        
        if(chDocente.isSelected()){
            System.out.println("Es docente ==== ");
            if("admin".equalsIgnoreCase(txtUsuario.getText()) && "admin".equalsIgnoreCase(txtClave.getText())){
                System.out.println("Docente Logueado correctamente ========== ");
                InterfazPrincipaProfesorlMDI iprofesor = new InterfazPrincipaProfesorlMDI();
                iprofesor.setVisible(true);//Hace visible la interfac Principal del profesor MDI
                this.dispose();//Cierra la ventana de cerrar sesion
                
            }else{
                Mensajes.mensajeAdvertencia("Usuario o clave incorrecto!");
            }
        }else{
            System.out.println("Intentando Loguearse como Estudiante ========= ");
            if(txtUsuario.getText() != null && txtClave.getText()!= null &&
                    !txtUsuario.getText().isEmpty() && !txtClave.getText().isEmpty()){
                
                Estudiante estudiante = jpa.buscarEstudiantePorUsuarioYClave(txtUsuario.getText(), txtClave.getText());
                if(estudiante == null){
                    Mensajes.mensajeAdvertencia("Estudiante no encontrado");
                }else{
                    InterfazPrincipalEstudianteMDI iestudiante = new InterfazPrincipalEstudianteMDI(estudiante);
                    iestudiante.setVisible(true);
                    this.dispose();
                }
            }else{
                System.out.println("Faltan campos === ");
                Mensajes.mensajeAdvertencia("Campos Obligatorios");
            }
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesionJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JCheckBox chDocente;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblImagenIniciarSesion;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
