/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicomfacauca.app.vista;

import com.unicomfacauca.app.modelo.Estudiante;
import com.unicomfacauca.app.vista.estudiante.JifActivo;
import com.unicomfacauca.app.vista.estudiante.PanelActivoReflexivo;
import com.unicomfacauca.app.vista.estudiante.PanelIniciar;
import com.unicomfacauca.app.vista.estudiante.PanelJuegoConcentrese;
import com.unicomfacauca.app.vista.estudiante.PanelSensorialIntuitivo2;
import com.unicomfacauca.app.vista.profesor.JifAdminEstudiante;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aleja
 */
public class InterfazPrincipalEstudianteMDI extends javax.swing.JFrame {

    private Estudiante estudianteLogin;    
    private List<PanelChild> listaJuegos;
    private Random randomGenerator;
    private PanelChild panelChildPrincipal;
    /**
     * Creates new form InterfazPrincipalEstudianteMDI
     */
    
           
    public InterfazPrincipalEstudianteMDI(Estudiante estudiante) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.estudianteLogin =  estudiante;
        Mensajes.mensajeAdvertencia("Bienvenido "+estudiante.getNombre()+" "+estudiante.getApellido()+"!");
        
        randomGenerator = new Random(); 
        panelChildPrincipal = generateListaPanelAleatorio();
    }

    
    private PanelChild generateListaPanelAleatorio(){
        listaJuegos = new ArrayList<>();
        listaJuegos.add(new PanelActivoReflexivo(desktopPane, null, jifActivoReflexivo));
        listaJuegos.add(new PanelSensorialIntuitivo2(desktopPane, null, jifActivoReflexivo));
        
        /*listaJuegos.add(new PanelJuegoDos(null, jifJuegos));
        listaJuegos.add(new PanelJuegoTres(null, jifJuegos));*/
        int tamanioLista  = listaJuegos.size();
        for (int i = 0; i < tamanioLista ; i++) {
            PanelChild panelInicial = listaJuegos.get(i);
            int posicionAleatorio = generateAleatorio(tamanioLista);            
            PanelChild panelAleatorio = listaJuegos.get(posicionAleatorio);            
            listaJuegos.set(i, panelAleatorio);
            listaJuegos.set(posicionAleatorio, panelInicial);                        
        }
        //Obtenemos el primero en caso de que haya solo uno        
        PanelChild panelConjugado =listaJuegos.get(0);        
        for (int i = 1; i < tamanioLista ; i++) {
            panelConjugado = listaJuegos.get(i-1);
            panelConjugado.panelChildSiguiente = listaJuegos.get(i);
        }

        return panelConjugado;
    }
    
    private int generateAleatorio(int size){
        return randomGenerator.nextInt(size);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jifInicio = new javax.swing.JInternalFrame();
        jifActivoReflexivo = new javax.swing.JInternalFrame();
        jifJuegoActivo = new javax.swing.JInternalFrame();
        jifJuegoReflexivo = new javax.swing.JInternalFrame();
        jifSensorialIntuitivo = new javax.swing.JInternalFrame();
        jifSensorial = new javax.swing.JInternalFrame();
        jifIntuitivo = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jifInicio.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifInicio.setName("JIF_NOMBRE"); // NOI18N
        jifInicio.setVisible(false);
        jifInicio.getContentPane().setLayout(new javax.swing.OverlayLayout(jifInicio.getContentPane()));
        desktopPane.add(jifInicio);
        jifInicio.setBounds(70, 310, 160, 70);
        jifInicio.getAccessibleContext().setAccessibleDescription("");

        jifActivoReflexivo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifActivoReflexivo.setName("JIF_ACTIVO_REFLEXIVO"); // NOI18N
        jifActivoReflexivo.setVisible(false);
        jifActivoReflexivo.getContentPane().setLayout(new javax.swing.OverlayLayout(jifActivoReflexivo.getContentPane()));
        desktopPane.add(jifActivoReflexivo);
        jifActivoReflexivo.setBounds(170, 200, 210, 80);

        jifJuegoActivo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifJuegoActivo.setName("JIF_JUEGO_ACTIVO"); // NOI18N
        jifJuegoActivo.setVisible(false);
        jifJuegoActivo.getContentPane().setLayout(new javax.swing.OverlayLayout(jifJuegoActivo.getContentPane()));
        desktopPane.add(jifJuegoActivo);
        jifJuegoActivo.setBounds(460, 330, 140, 70);

        jifJuegoReflexivo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifJuegoReflexivo.setName("JIF_JUEGO_REFLEXIVO"); // NOI18N
        jifJuegoReflexivo.setVisible(false);
        jifJuegoReflexivo.getContentPane().setLayout(new javax.swing.OverlayLayout(jifJuegoReflexivo.getContentPane()));
        desktopPane.add(jifJuegoReflexivo);
        jifJuegoReflexivo.setBounds(260, 320, 140, 70);

        jifSensorialIntuitivo.setVisible(false);
        jifSensorialIntuitivo.getContentPane().setLayout(new javax.swing.OverlayLayout(jifSensorialIntuitivo.getContentPane()));
        desktopPane.add(jifSensorialIntuitivo);
        jifSensorialIntuitivo.setBounds(60, 370, 22, 33);

        jifSensorial.setVisible(false);
        jifSensorial.getContentPane().setLayout(new javax.swing.OverlayLayout(jifSensorial.getContentPane()));
        desktopPane.add(jifSensorial);
        jifSensorial.setBounds(100, 370, 22, 33);

        jifIntuitivo.setVisible(false);
        jifIntuitivo.getContentPane().setLayout(new javax.swing.OverlayLayout(jifIntuitivo.getContentPane()));
        desktopPane.add(jifIntuitivo);
        jifIntuitivo.setBounds(150, 370, 22, 33);

        getContentPane().add(desktopPane);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Iniciar Prueba");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        jifInicio.setVisible(true);        
        jifInicio.add(new PanelIniciar(desktopPane, panelChildPrincipal, jifInicio));        
        jifInicio.pack();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JInternalFrame jifActivoReflexivo;
    private javax.swing.JInternalFrame jifInicio;
    private javax.swing.JInternalFrame jifIntuitivo;
    private javax.swing.JInternalFrame jifJuegoActivo;
    private javax.swing.JInternalFrame jifJuegoReflexivo;
    private javax.swing.JInternalFrame jifSensorial;
    private javax.swing.JInternalFrame jifSensorialIntuitivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables

}
