/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicomfacauca.app.vista.estudiante;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;

/**
 *
 * @author aleja
 */
public class JifActivo extends javax.swing.JInternalFrame {

    
    private PanelJuegoConcentrese panel;
    
    public JifActivo(JDesktopPane desktopPane) {
        try {
            initComponents();
            this.setMaximum(false);
            panel = new PanelJuegoConcentrese(this);
            panel.setVisible(true);
            add(panel);
            pack();
            desktopPane.add(this);
            desktopPane.setVisible(true);
            System.out.println("HOLA ====================== JIFACTIVO ============= ");
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JifActivo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
