/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicomfacauca.app.vista.estudiante;

import com.unicomfacauca.app.vista.PanelChild;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author aleja
 */
public class PanelActivoReflexivo extends PanelChild {

        
    
    private JifActivo adasds;
    //private PanelJuegoLaberinto panelReflexivo;
    
    
    public PanelActivoReflexivo(JDesktopPane desktopPane, PanelChild panelSiguiente, JInternalFrame jifPanelPrincipal) {
        
        super(desktopPane, panelSiguiente, jifPanelPrincipal);
        System.out.println("Que más ==== "+panelSiguiente);
        initComponents();        
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/imagenes/activo.jpg"));        
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/imagenes/reflexivo.jpg"));        
        Icon icon1 = new ImageIcon(imagen1.getImage().getScaledInstance(255,185, Image.SCALE_DEFAULT)); 
        Icon icon2 = new ImageIcon(imagen2.getImage().getScaledInstance(255,185, Image.SCALE_DEFAULT)); 
        btnActivo.setIcon(icon1);
        btnReflexivo.setIcon(icon2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActivo = new javax.swing.JButton();
        btnReflexivo = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0));

        btnActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivoActionPerformed(evt);
            }
        });
        add(btnActivo);

        btnReflexivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReflexivoActionPerformed(evt);
            }
        });
        add(btnReflexivo);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivoActionPerformed
        System.out.println(" ================================= Aguas Negras === "+jifPanelPrincipal);
        JifActivo j = new JifActivo(desktopPane); 
        j.setVisible(true);
        jifPanelPrincipal.setVisible(false);
    }//GEN-LAST:event_btnActivoActionPerformed

    private void btnReflexivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReflexivoActionPerformed
        //panelReflexivo = new  PanelJuegoLaberinto(panelChildSiguiente, jifPanelPrincipal, jifPanelVisualiza2);//Aqui dos porque llama al segundo java internal frame
        //panelReflexivo.setVisible(true);                 
        //panelReflexivo.add(panelActivo);
        //panelReflexiv jifPanelVisualiza1.pack(); 
    }//GEN-LAST:event_btnReflexivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivo;
    private javax.swing.JButton btnReflexivo;
    // End of variables declaration//GEN-END:variables
}
